SELECT AOUT.ANIMAL_ID, AOUT.ANIMAL_TYPE, AOUT.NAME
FROM ANIMAL_INS AIN JOIN ANIMAL_OUTS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AIN.SEX_UPON_INTAKE LIKE 'Intact%'
AND AOUT.SEX_UPON_OUTCOME IN ('Neutered Male', 'Spayed Female')