SELECT PRD.PRODUCT_ID, PRD.PRODUCT_NAME, (SUM(ORD.AMOUNT) * PRD.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT PRD JOIN FOOD_ORDER ORD
ON PRD.PRODUCT_ID = ORD.PRODUCT_ID
WHERE DATE_FORMAT(ORD.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
